# Generated by Django 4.0 on 2021-12-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'All Jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name_plural': 'Job Categories'},
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
